---
title: Project Review
author: Erick Mollinedo
date: 04-24-2024
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Factors influencing abundance & virus isolation in mosquitoes

Name of project author(s): Andrew Ruiz

Name of project reviewer: Erick Mollinedo


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

The background is really strong, you included a lot of important information. However, I would suggest to shape the background/introduction section to look more like the Introduction section from a peer reviewed article. This means, have it in a single section and each paragraph represents a specific topic, meanwhile the last one has your justification (Questions/Hypothesis). I would also add references to your questions/hypothesis section. But as I said, this is a suggestion, the format you used looks good to me but I am not completely sure if this is what the instructor and TAs are expecting for the final manuscript document.

### Summary assessment (PICK ONE, DELETE THE OTHERS)

* strong contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

I am not clear what your questions for this project are. In your manuscript, you listed 3 questions but then you mention that they will not be addressed in the project. Then you mention that they will hopefully inform research that wil answer the following questions, but I am not sure what are these other additional questions. Please clarify on the background section of your manuscript what are your aims, described as your questions/hypothesis.

### Summary assessment

* question/hypotheses somewhat explained



## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

Good job describing the sources of the data, I appreciate the thoroughness of all variables. However, I would suggest to make it simpler (maybe not go into much detail) and list them as part of the Methods section in the main Manuscript. Maybe you could move most of it into the description of the data sources and what each variable means in the Supplementary material section, so you can go deeper detailing the descriptions.

### Summary assessment

* source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

For what I saw in the main Manuscript document, I sense all the exploratory analyses are correct. I would suggest to move them to the Supplementary material document, since this should not be part of your results in the main Manuscript. Also, there were some errors while running the data processing code `MADAproject_pt2_ruiz.qmd`, but I will go deeper into details in later sections. I also suggest to add an explanation (in the processing code file) before each code chunk that describes what is the purpose of what you are coding, for example: "Load the file, merge columns and then save it as a data frame...". So far, you list what the dataset includes and the source, but I believe this should go into the Supplementary material.

### Summary assessment

* some weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

You included all the ML modeling components in my opinion and evaluated different models. However, it was not clear to me what you were modeling since your main questions/hypothesis are not clear on the Manuscript. I saw the following question in the analysis.qmd code that I thing is the main question you are trying to answer, correct? 'Does the total precipitation in April, May, and June influence the date of the first positive test?' If so, please specify it in your Manuscript. Also, add a short description of what you are aiming to to before each code chunk, and after each code chunk just add a brief explanation of what you observed/what those results mean. This will be helpful to you when integrating everything into the Results section.

### Summary assessment

* strong and reasonable analysis


## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

The results are missing in the main Manuscript. I believe you have those in your `analysis.qmd` file, but they have not been incorporated to the Manuscript file. It also caught my attention that you mention some of the results of conducting modeling under the 'Basic statistical analysis' section in Methods, which I believe these are part of the results. So I would suggest in general, to review the sections of the manuscript file so they are correctly labeled: Background, Methods, Results, Discussion. 

### Summary assessment

* results are poorly presented, hard to understand, poor quality


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

Lacking conclusions and poor discussion. This is due to the main results not being included, I believe you have those in your code files but you did not include them into the manuscript.

### Summary assessment

* major parts of discussion missing or wrong 



## Further comments

Overall I think you understand the whole process of data exploring and analysis, but you missed to merge all of your work in the manuscript. You have done a very good job stating the initial parts of the analysis, and I also suggest to move some of them to the Supplementary materials (most of the details about data processing and variables descriptions). Focus on working on the Manuscript so it renders as a complete peer reviewed paper with all his sections: Abstract, Introduction, Methods, Results, Discussion, Conclusions. This is what summarizes everything located in your code files.
Also, clearly state your hypothesis/questions, so all of us understand the rationale of your project.



# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

I believe everything is right in his place. By having a glimpse, the folders with data have a lot of files, so I recommend carefully to select which data will be saved as processed data, you might not need all of those to be saved (or maybe you do, just a thought). Also, there were a couple .csv files floating around, but it's ok, it happens to all of us. Just check if these are not essential and maybe you could delete them. Also, make sure to update your Readme files so they show the correct structure of your folders.

### Summary assessment

* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

I suggest to include not just titles of what each chunk of code is doing. I would suggest to add a description of what you are aiming to do in the code (I mentioned before an example of how to do it). Also, you should add a brief sentence or line, explaining the results of your code when doing data exploring or analysis, so it is clear why you made decisions and why you decided to move to a new direction.

### Summary assessment

* decently documented with some gaps



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

Small parts of your codes didn't run, but overall didn't stopped the majority of the code to being executed. Make sure your R objects are correctly referenced, this is one of the first things that I noticed like for example the object `pcr_data_expanded`, which showed to me as an error that the object is not available in line #113 of the `MADAproject_pt2_ruiz.qmd` file. Another error I saw was when you were loading certain objects, for example: `trap_location = read_excel(file_path_trap)` showed me as an error that the path does not exist. To correct this, I suggest you implement loading the data using relative paths, instead of absolute paths using the `here()` function, something like this: `trap_location <- read_excel(here(file_path_trap))`.


### Summary assessment

* small parts not reproducible or required manual intervention 



## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

By looking at the codes, you implemented various ML modeling methods and assessments. Good job on this!
And related as previous comments, make sure to clearly state your questions/hypothesis so it is clear why you did all the statistical analysis as described in your EDA and statistical analysis codes.

### Summary assessment

* strong level of thorougness


## Further comments

A suggestion: To simplify when loading your packages, check which packages are already included in main ones. For example, if you load `tidyverse` this will already include `ggplot2`, `dplyr`, `lubridate`, same goes for `tidymodels`, which includes packages such as `parsnip`, `yardstick` and others. This way, you avoid repeating or re-loading certain packages.
Also to reiterate, make sure your code runs smoothly when loading, saving files using functions with relative paths, and add a little more description into your code chunks from all your coding files.


