---
title: Project Review Factors Influencing Abundance & Virus Isolation in Mosquitoes
author: Clarke Miller
date: 26 April 2024
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: **Factors Influencing Abundance & Virus Isolation in Mosquitoes**
Subtitle:  ***Which environmental, ecological, and temporal factors impact mosquito populations***

Name of project author(s):  Andrew Ruiz

Name of project reviewer:  Clarke Miller


## Background, Context and Motivation

*How well is the context of the project described?* 

Very well.  This looks great.

*Is a comprehensive background, including summary of previous/related work given?* 

Yes.  Very much so.

*Is the project well placed into the context of existing work (including proper referencing of existing work).* 
Yes, very much so.

*Is it clear why the project was undertaken and what new information it hopes to provide?*

Yes.  Very much so.

***Personal Message***  
Andrew, this looks great.  From our conversations over Discord, you were very critical of your own work.  This project looks awesome.  You have a couple of things to polish off, but, wow.  You obviously have the topic covered, you have the coding skills, you got this.  


### Feedback and Comments

No real feedback on this part.  You did a great job in this category.

### Summary assessment (PICK ONE, DELETE THE OTHERS)

* strong contextualization and motivation


## Question description

*How well and clear are the question(s)/hypotheses the project aims to address described?*

Very clear.  The questions are very well outlined and discussed.

*Is it clear how the questions relate to the data?*

Yes.


### Feedback and Comments

No real feedback on this part.  You did a great job in this category.

### Summary assessment

* question/hypotheses fully clear


## Data description

*How well is the data overall described?*

Very well.  I would like to see a table summary of the data.  

*Is the source provided?* 

Yes.

*Is a codebook or other meta-information available that makes it clear what the data is?* 

I did not see one.  



### Feedback and Comments

No real feedback on this part.  You did a great job in this category.  Just maybe add a summary table and if there is a codebook add it to the raw data and label it.

### Summary assessment

* source and overall structure of data well explained


## Data wrangling and exploratory analysis

*How well is the data cleaned/processed and explored?* 

Yes.  You did a great job with this.

*Are all steps reasonable and well explained?*

Yes.  The steps are reasonable and explained.

*Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?*

At this point in time, no.  There are placeholders for this material in the document.


### Feedback and Comments

No real feedback on this part.  You did a great job in this category.  Despite being a work in progress, this section is well done.

### Summary assessment

* essentially no weaknesses in wrangling and exploratory component



## Appropriateness of Analysis

*Were the analysis methods appropriate for the data? Was the analysis done properly?*

Yes, I believe that they were.  I am not an expert on this topic, but the analysis looked reasonable and properly done.


*Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?*

Again, I am not an expert on this topic.  The analysis looked appropriate for the data type.  Yes, the data and analysis were explained well. 


### Feedback and Comments

No real feedback on this part.  You did a great job in this category.  The description of the intended analysis is appropriate.

### Summary assessment

* strong and reasonable analysis/description.

## Presentation

*How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality?*

The results were presented in a table format.  The results compared several types of model for the desired data.  The table included RMSE data for training and test data.  No figures of the analysis were made.

### Feedback and Comments

No real feedback on this part.  You did a great job in this category.

### Summary assessment

* results are presented ok, with room for improvement

At this point, this section of the document seems incomplete.  I can see a need for tables describing the output discussed in the basic data analysis section.  Plus, maybe some descriptive figures of the analysis if possible?

## Discussion/Conclusions

*Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?*

Yes.  The conclusions are discussed, the strengths and limitations of the data and analyses are discussed.

### Feedback and Comments

No real feedback on this section.  The section looked generally complete.

### Summary assessment

* strong, complete and clear discussion


## Further comments

The basic bones of the project look good.  It is obvious that a good deal of work has gone into the paper.

# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure

*Is the project well structured? Are files in well labeled folders?* 

Yes.

*Do files have reasonable names?*

Yes.

*Are all "junk" files not needed for analysis/reproduction removed?* 

Not at this time.  There are still a lot of extra files in the repo.

*By just looking at files and folders, can you get an idea of how things fit together?*
 
 Yes.


### Feedback and Comments

At this point, there are a lot of "sandbox" files still around.

### Summary assessment

* mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)



## Documentation 

*How well is the project documented?* 

Fairly well.  The readme file is being used... it could use a better description.

*Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files?*

Yes, as far as the work has been done.  

### Feedback and Comments

I think that no project can be documented well enough.  This one needs a bit more work in that area.  There are still a a lot of readme files talking about how the project will look when it's finished.  Of course, that might just be github acting up again.  

### Summary assessment

* decently documented with some gaps




## Reproducibility

*Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?*

Yes.  Everything looks complete and it runs.  

### Feedback and Comments

I like how you piled all the code into a single R folder.  It took a minute for me to find it because it wasn't the format that my other review used.  I think that is a cleaner way to organize the coding sections.  


### Summary assessment
 
* fully reproducible without issues


## Thoroughness

*How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?*

The overall study looks very thorough and complete.  Again, I am not an expert in this area, but everything looked reasonable and well thought out.  All the salient areas seemed to be addressed.

### Feedback and Comments

No real feedback on this section.  The section looked generally complete.

### Summary assessment

* decent level of thoroughness



## Further comments

_Add any other comments regarding the overall project here. Write anything you think can help your classmate improve their project._


Just finish this project off the way you've described and it will be great! 


